name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate
    
    # Tambahkan 2 baris ini untuk memaksa izin write
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: NekoSukuriputo
          THEME: tokyonight
