name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate
    
    permissions:
      contents: write

    steps:
      # Langkah 1: Ambil kode dari repositorimu
      - uses: actions/checkout@v3
      
      # Langkah 2: Jalankan engine resmi agar path git add tidak error
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: NekoSukuriputo
          THEME: tokyonight
